import logging

from BaseClasses import Item


def ItemFactory(items, player):
    ret = []
    singleton = False
    if isinstance(items, str):
        items = [items]
        singleton = True
    for item in items:
        if item in item_table:
            advancement, priority, type, code, pedestal_hint, pedestal_credit, sickkid_credit, zora_credit, witch_credit, fluteboy_credit, hint_text = item_table[item]
            ret.append(Item(item, advancement, priority, type, code, pedestal_hint, pedestal_credit, sickkid_credit, zora_credit, witch_credit, fluteboy_credit, hint_text, player))
        else:
            logging.getLogger('').warning('Unknown Item: %s', item)
            return None

    if singleton:
        return ret[0]
    return ret


# Format: Name: (Advancement, Priority, Type, ItemCode, Pedestal Hint Text, Pedestal Credit Text, Sick Kid Credit Text, Zora Credit Text, Witch Credit Text, Flute Boy Credit Text, Hint Text)
item_table = {'Bow': (True, False, None, 0x0B, 'Bow!\nJoin the archer class!', 'the stick and twine', 'arrow-slinging kid', 'arrow sling for sale', 'witch and robin hood', 'archer boy shoots again', 'The Bow'),
              'Progressive Bow': (True, False, None, 0x64, 'Bow!\nJoin the archer class!', 'the stick and twine', 'arrow-slinging kid', 'arrow sling for sale', 'witch and robin hood', 'archer boy shoots again', 'A Bow'),
              'Book of Mudora': (True, False, None, 0x1D, 'This is a\nparadox?!', 'and the story book', 'the scholarly kid', 'moon runes for sale', 'drugs for literacy', 'book-worm boy can read again', 'The Book'),
              'Hammer': (True, False, None, 0x09, 'stop\nhammer time!', 'and m c hammer', 'hammer-smashing kid', 'm c hammer for sale', 'stop...   hammer time', 'stop, hammer time', 'The Hammer'),
              'Hookshot': (True, False, None, 0x0A, 'Hookshot!\nBOING! BOING!', 'and the tickle beam', 'tickle-monster kid', 'tickle beam for sale', 'witch and tickle boy', 'beam boy tickles again', 'The Hookshot'),
              'Magic Mirror': (True, False, None, 0x1A, 'Mirror!\nTake some time to\nreflect on this moment!', 'the face reflector', 'the narcissistic kid', 'your face for sale', 'trades looking-glass', 'narcissistic boy is happy again', 'The Mirror'),
              'Ocarina': (True, False, None, 0x14, 'Ocarina!\nA Flute by another name', 'and the duck call', 'the duck-call kid', 'duck call for sale', 'duck-calls for trade', 'ocarina boy plays again', 'The Flute'),
              'Pegasus Boots': (True, False, None, 0x4B, 'Pegasus Boots!\nGotta go fast!', 'and the sprint shoes', 'the running-man kid', 'sprint shoe for sale', 'shrooms for speed', 'gotta-go-fast boy runs again', 'The Boots'),
              'Power Glove': (True, False, None, 0x1B, 'Glove!\nNow you can\nlift weak stuff!', 'and the grey mittens', 'body-building kid', 'lift glove for sale', 'fungus for gloves', 'body-building boy lifts again', 'The Glove'),
              'Cape': (True, False, None, 0x19, 'Cape!\nInvisbility cloak activate!', 'the camouflage cape', 'red riding-hood kid', 'red hood for sale', 'hood from a hood', 'dapper boy hides again', 'The Cape'),
              'Mushroom': (True, False, None, 0x29, 'Mushroom!\nDon\'t eat it. Find a witch.', 'and the legal drugs', 'the drug-dealing kid', 'legal drugs for sale', 'shroom swap', 'shroom boy sells drugs again', 'The Mushroom'),
              'Shovel': (True, False, None, 0x13, 'Shovel!\nCan you dig it?', 'and the spade', 'archaeologist kid', 'dirt spade for sale', 'can you dig it', 'shovel boy digs again', 'The Shovel'),
              'Lamp': (True, False, None, 0x12, 'Lamp!\nYou can see in the dark,\nand light torches.', 'and the flashlight', 'light-shining kid', 'flashlight for sale', 'fungus for illumination', 'illuminated boy can see again', 'The Lamp'),
              'Magic Powder': (True, False, None, 0x0D, 'Powder!\nSprinkle it on a dancing pickle!', 'and the magic sack', 'the sack-holding kid', 'magic sack for sale', 'the witch and assistant', 'magic boy plays marbles again', 'The Powder'),
              'Moon Pearl': (True, False, None, 0x1F, 'Moon Pearl!\nRabbit Be Gone!', 'and the jaw breaker', 'fortune-telling kid', 'lunar orb for sale', 'shrooms for moon rock', 'moon boy plays ball again', 'The Moon Pearl'),
              'Cane of Somaria': (True, False, None, 0x15, 'Cane of Somaria!\nMake blocks, throw blocks', 'and the red blocks', 'the block-making kid', 'block stick for sale', 'block stick for trade', 'cane boy makes blocks again', 'The Red Cane'),
              'Fire Rod': (True, False, None, 0x07, 'Fire Rod!\nI\'m burning for you!', 'and the flamethrower', 'fire-starting kid', 'rage rod for sale', 'fungus for rage-rod', 'firestarter boy burns again', 'The Fire Rod'),
              'Flippers': (True, False, None, 0x1E, 'Flippers!\nFancy a swim!', 'and the toewebs', 'the swimming kid', 'finger webs for sale', 'shrooms let you swim', 'swimming boy swims again', 'The Flippers'),
              'Ice Rod': (True, False, None, 0x08, 'Ice Rod!\nActivate Freeze Ray!', 'and the freeze ray', 'the ice-bending kid', 'freeze ray for sale', 'fungus for ice-rod', 'ice-cube boy freezes again', 'The Ice Rod'),
              'Titans Mitts': (True, False, None, 0x1C, 'Mitts!\nLift ALL the rocks!', 'and the golden glove', 'body-building kid', 'carry glove for sale', 'fungus for bling-gloves', 'body-building boy has gold again', 'The Mitts'),
              'Ether': (True, False, None, 0x10, 'Ether!\nLet\'s cool things down!', 'and the bolt coin', 'coin-collecting kid', 'bolt coin for sale', 'shrooms for bolt-coin', 'medallion boy sees floor again', 'Ether'),
              'Bombos': (True, False, None, 0x0F, 'Bombos!\nExplosions! Fire!\nBurn it all!', 'and the swirly coin', 'coin-collecting kid', 'swirly coin for sale', 'shrooms for swirly-coin', 'medallion boy melts room again', 'Bombos'),
              'Quake': (True, False, None, 0x11, 'Quake!\nLet\'s shake the ground!', 'and the wavy coin', 'coin-collecting kid', 'wavy coin for sale', 'shrooms for wavy-coin', 'medallion boy shakes dirt again', 'Quake'),
              'Bottle': (True, False, None, 0x16, 'Bottle!\nStore all manner of things!', 'and the terrarium', 'the terrarium kid', 'terrarium for sale', 'special promotion', 'bottle boy has terrarium again', 'A Bottle'),
              'Bottle (Red Potion)': (True, False, None, 0x2B, 'Red Potion!\nFill your hearts!', 'and the red goo', 'the liquid kid', 'potion for sale', 'free samples', 'bottle boy has red goo again', 'A Bottle'),
              'Bottle (Green Potion)': (True, False, None, 0x2C, 'Green Potion!\nRestore your magic!', 'and the green goo', 'the liquid kid', 'potion for sale', 'free samples', 'bottle boy has green goo again', 'A Bottle'),
              'Bottle (Blue Potion)': (True, False, None, 0x2D, 'Blue Potion!\nHeal and restore!', 'and the blue goo', 'the liquid kid', 'potion for sale', 'free samples', 'bottle boy has blue goo again', 'A Bottle'),
              'Bottle (Fairy)': (True, False, None, 0x3D, 'Fairy Bottle\nI\'ll save your life!', 'and the captive', 'the tingle kid', 'hostage for sale', 'fairy dust and shrooms', 'bottle boy has friend again', 'A Bottle'),
              'Bottle (Bee)': (True, False, None, 0x3C, 'Bee Bottle\nI\'ll sting your enemies a bit!', 'and the sting buddy', 'the beekeeper kid', 'insect for sale', 'shroom pollenation', 'bottle boy has mad bee again', 'A Bottle'),
              'Bottle (Good Bee)': (True, False, None, 0x48, 'Good Bee Bottle\nI\'ll sting your enemies\na whole lot!', 'and the sparkle sting', 'the beekeeper kid', 'insect for sale', 'shroom pollenation', 'bottle boy has beetor again', 'A Bottle'),
              'Master Sword': (True, False, 'Sword', 0x50, 'Master Sword!\nEvil\'s bane!', 'and the master sword', 'sword-wielding kid', 'glow sword for sale', 'fungus for blue slasher', 'sword boy fights again', 'The Master Sword'),
              'Tempered Sword': (True, False, 'Sword', 0x02, 'Tempered Sword!\nMore slashy!', 'the tempered sword', 'sword-wielding kid', 'flame sword for sale', 'fungus for red slasher', 'sword boy fights again', 'The Tempered Sword'),
              'Sword and Shield': (True, False, 'Sword', 0x00, 'Sword and Shield!\nUncle sword ahoy!', 'the sword and shield', 'sword and shield-wielding kid', 'training set for sale', 'fungus for training set', 'sword and shield boy fights again', 'The Sword and Shield'),
              'Fighter Sword': (True, False, 'Sword', 0x49, 'Fighter Sword!\nStarter level slashy!', 'the tiny sword', 'sword-wielding kid', 'tiny sword for sale', 'fungus for tiny slasher', 'sword boy fights again', 'The Small Sword'),
              'Golden Sword': (True, False, 'Sword', 0x03, 'Golden Sword!\nBest slashy!', 'and the butter sword', 'sword-wielding kid', 'butter for sale', 'cap churned to butter', 'sword boy fights again', 'The Golden Sword'),
              'Progressive Sword': (True, False, 'Sword', 0x5E, 'Sword!\nA better sword for your time!', 'the unknown sword', 'sword-wielding kid', 'sword for sale', 'fungus for some slasher', 'sword boy fights again', 'A sword'),
              'Progressive Glove': (True, False, None, 0x61, 'Glove!\nLift more than you can now!', 'and the lift upgrade', 'body-building kid', 'some glove for sale', 'fungus for gloves', 'body-building boy lifts again', 'A Glove'),
              'Silver Arrows': (True, False, None, 0x58, 'Silver Arrows!\nDefeat Ganon faster!', 'and the ganonsbane', 'ganon-killing kid', 'ganon doom for sale', 'fungus for pork', 'archer boy shines again', 'The Silver Arrows'),
              'Green Pendant': (True, False, 'Crystal', [0x04, 0x38, 0x62, 0x00, 0x69, 0x37], None, None, None, None, None, None, None),
              'Blue Pendant': (True, False, 'Crystal', [0x02, 0x34, 0x60, 0x00, 0x69, 0x39], None, None, None, None, None, None, None),
              'Red Pendant': (True, False, 'Crystal', [0x01, 0x32, 0x60, 0x00, 0x69, 0x38], None, None, None, None, None, None, None),
              'Triforce': (True, False, None, 0x6A, 'Triforce\nGrab me to win!', 'and the triforce', 'victorious kid', 'victory for sale', 'fungus for the win', 'greedy boy wins game again', 'The Triforce'),
              'Power Star': (True, False, None, 0x6B, 'Power Star\nA small step\ntowards victory!', 'and the power star', 'star-struck kid', 'star for sale', 'see stars with shroom', 'mario powers up again', 'A Power Star'),
              'Triforce Piece': (True, False, None, 0x6C, 'Triforce Piece\nA small step\ntowards victory!', 'and the thirdforce', 'triangular kid', 'triangle for sale', 'fungus for triangle', 'wise boy has triangle again', 'A Triforce Piece'),
              'Crystal 1': (True, False, 'Crystal', [0x02, 0x34, 0x64, 0x40, 0x7F, 0x20], None, None, None, None, None, None, None),
              'Crystal 2': (True, False, 'Crystal', [0x10, 0x34, 0x64, 0x40, 0x79, 0x20], None, None, None, None, None, None, None),
              'Crystal 3': (True, False, 'Crystal', [0x40, 0x34, 0x64, 0x40, 0x6C, 0x20], None, None, None, None, None, None, None),
              'Crystal 4': (True, False, 'Crystal', [0x20, 0x34, 0x64, 0x40, 0x6D, 0x20], None, None, None, None, None, None, None),
              'Crystal 5': (True, False, 'Crystal', [0x04, 0x32, 0x64, 0x40, 0x6E, 0x20], None, None, None, None, None, None, None),
              'Crystal 6': (True, False, 'Crystal', [0x01, 0x32, 0x64, 0x40, 0x6F, 0x20], None, None, None, None, None, None, None),
              'Crystal 7': (True, False, 'Crystal', [0x08, 0x34, 0x64, 0x40, 0x7C, 0x20], None, None, None, None, None, None, None),
              'Single Arrow': (False, False, None, 0x43, 'Single Arrow!\nDestiny awaits!', 'and the arrow', 'stick-collecting kid', 'sewing needle for sale', 'fungus for arrow', 'archer boy sews again', 'An arrow'),
              'Arrows (10)': (False, False, None, 0x44, '10 Arrows\nAn archer\'s bailout!', 'and the arrow pack', 'stick-collecting kid', 'sewing kit for sale', 'fungus for arrows', 'archer boy sews again', 'Ten arrows'),
              'Arrow Upgrade (+10)': (False, False, None, 0x54, '10 Arrow Upgrade\nGain 10 more arrow capacity!', 'and the quiver', 'quiver-enlarging kid', 'arrow boost for sale', 'witch and more skewers', 'upgrade boy sews more again', 'An arrow capacity upgrade'),
              'Arrow Upgrade (+5)': (False, False, None, 0x53, '5 Arrow Upgrade\nGain 5 more arrow capacity!', 'and the quiver', 'quiver-enlarging kid', 'arrow boost for sale', 'witch and more skewers', 'upgrade boy sews more again', 'An arrow capacity upgrade'),
              'Single Bomb': (False, False, None, 0x27, '1 Bomb\nBoom boom pow!', 'and the explosion', 'the bomb-holding kid', 'firecracker for sale', 'blend fungus into bomb', '\'splosion boy explodes again', 'A bomb'),
              'Bombs (3)': (False, False, None, 0x28, '3 Bombs\nExplosions!\nIn a handy 3-pack', 'and the explosions', 'the bomb-holding kid', 'firecrackers for sale', 'blend fungus into bombs', '\'splosion boy explodes again', 'Three bombs'),
              'Bombs (10)': (False, False, None, 0x31, '10 Bombs\nExplosions!\nIn a thrifty 10-pack', 'and the explosions', 'the bomb-holding kid', 'firecrackers for sale', 'blend fungus into bombs', '\'splosion boy explodes again', 'Ten bombs'),
              'Bomb Upgrade (+10)': (False, False, None, 0x52, '10 Bomb Upgrade\nGain 10 more bomb capacity!', 'and the bomb bag', 'boom-enlarging kid', 'bomb boost for sale', 'the shroom goes boom', 'upgrade boy explodes more again', 'A bomb capacity upgrade'),
              'Bomb Upgrade (+5)': (False, False, None, 0x51, '5 Bomb Upgrade\nGain 5 more bomb capacity!', 'and the bomb bag', 'boom-enlarging kid', 'bomb boost for sale', 'the shroom goes boom', 'upgrade boy explodes more again', 'A bomb capacity upgrade'),
              'Blue Mail': (False, True, None, 0x22, 'Blue Mail!\nLess damage activate!', 'and the banana hat', 'the protected kid', 'banana hat for sale', 'the clothing store', 'tailor boy banana hatted again', 'The Blue Mail'),
              'Red Mail': (False, True, None, 0x23, 'Red Mail!\nEven less damage!', 'and the eggplant hat', 'well-protected kid', 'purple hat for sale', 'the nice clothing store', 'tailor boy fears nothing again', 'The Red Mail'),
              'Progressive Armor': (False, True, None, 0x60, 'Upgrade Mail!\nNot the kind you read!', 'and the unknown hat', 'the protected kid', 'new hat for sale', 'the clothing store', 'tailor boy has threads again', 'Some Armor'),
              'Blue Boomerang': (True, False, None, 0x0C, 'Blue Boomerang!\nAlways comes back!', 'and the bluemarang', 'the bat-throwing kid', 'bent stick for sale', 'fungus for puma-stick', 'throwing boy plays fetch again', 'The Blue Boomerang'),
              'Red Boomerang': (True, False, None, 0x2A, 'Red Boomerang!\nAlways comes back!', 'and the badmarang', 'the bat-throwing kid', 'air foil for sale', 'fungus for return-stick', 'magical boy plays fetch again', 'The Red Boomerang'),
              'Blue Shield': (False, True, None, 0x04, 'Blue Shield\nBlock rocks!', 'and the stone blocker', 'shield-wielding kid', 'shield for sale', 'fungus for shield', 'shield boy defends again', 'The Blue Shield'),
              'Red Shield': (False, True, None, 0x05, 'Red Shield\nBlock fireballs!', 'and the shot blocker', 'shield-wielding kid', 'fire shield for sale', 'fungus for fire shield', 'shield boy defends again', 'The Red Shield'),
              'Mirror Shield': (True, False, None, 0x06, 'Mirror Shield\nBlock lasers!', 'and the laser blocker', 'shield-wielding kid', 'face shield for sale', 'fungus for face shield', 'shield boy defends again', 'The Mirror Shield'),
              'Progressive Shield': (True, False, None, 0x5F, 'Shield\nA better shield for your time!', 'and the new shield', 'shield-wielding kid', 'shield for sale', 'fungus for shield', 'shield boy defends again', 'A Shield'),
              'Bug Catching Net': (True, False, None, 0x21, 'Bug Net!\nCatch all manner\nof things!', 'and the bee catcher', 'the bug-catching kid', 'stick web for sale', 'fungus for butterflies', 'wrong boy catches bees again', 'The Bug Net'),
              'Cane of Byrna': (True, False, None, 0x18, 'Cane of Byrna!\nSwirly protection!', 'and the bad cane', 'the spark-making kid', 'spark stick for sale', 'spark-stick for trade', 'cane boy encircles again', 'The Blue Cane'),
              'Boss Heart Container': (False, False, None, 0x3E, 'Heart Container!\nHealth Increased!', 'and the full heart', 'the life-giving kid', 'love for sale', 'fungus for life', 'life boy feels love again', 'A Heart'),
              'Sanctuary Heart Container': (False, False, None, 0x3F, 'Heart Container!\nHealth Increased!', 'and the full heart', 'the life-giving kid', 'love for sale', 'fungus for life', 'life boy feels love again', 'A Heart'),
              'Piece of Heart': (False, False, None, 0x17, 'Heart Piece!\nOne step closer\nto more health!', 'and the broken heart', 'the life-giving kid', 'little love for sale', 'fungus for life', 'life boy feels some love again', 'A Heart Piece'),
              'Rupee (1)': (False, False, None, 0x34, 'Rupees!\nNeat I guess?', 'the pocket change', 'poverty-struck kid', 'life lesson for sale', 'buying cheap drugs', 'destitute boy has snack again', 'A green rupee'),
              'Rupees (5)': (False, False, None, 0x35, 'Rupees!\nNeat I guess?', 'the pocket change', 'poverty-struck kid', 'life lesson for sale', 'buying cheap drugs', 'destitute boy has snack again', 'A blue rupee'),
              'Rupees (20)': (False, False, None, 0x36, 'Rupees!\nThat\'s alright.', 'and the couch cash', 'the piggy-bank kid', 'life lesson for sale', 'the witch buying drugs', 'destitute boy has lunch again', 'A red rupee'),
              'Rupees (50)': (False, False, None, 0x41, 'Rupees!\nThat\'s neat!', 'and the rupee pile', 'the well-off kid', 'life lesson for sale', 'buying okay drugs', 'destitute boy has dinner again', 'Fifty rupees'),
              'Rupees (100)': (False, False, None, 0x40, 'Rupees!\nThat\'s awesome!', 'and the rupee stash', 'the kind-of-rich kid', 'life lesson for sale', 'buying good drugs', 'affluent boy goes drinking again', 'One hundred rupees'),
              'Rupees (300)': (False, False, None, 0x46, 'Rupees!\nThat\'s fantastic!', 'and the rupee hoard', 'the really-rich kid', 'life lesson for sale', 'buying the best drugs', 'fat-cat boy is rich again', 'Three hundred rupees'),
              'Rupoor': (False, False, None, 0x59, 'Rupoor!\nI\'ll take your rupees!', 'and the toll-booth', 'the toll-booth kid', 'double loss for sale', 'witch stole your rupees', 'affluent boy steals rupees', 'A rupoor'),
              'Red Clock': (False, True, None, 0x5B, 'Red Clock!\nA waste of time.', 'the ruby clock', 'the ruby-time kid', 'red time for sale', 'for ruby time', 'moment boy travels time again', 'A red clock'),
              'Blue Clock': (False, True, None, 0x5C, 'Blue Clock!\nA bit of time!', 'the sapphire clock', 'sapphire-time kid', 'blue time for sale', 'for sapphire time', 'moment boy time travels again', 'A blue clock'),
              'Green Clock': (False, True, None, 0x5D, 'Green Clock!\nTons of time!', 'the emerald clock', 'the emerald-time kid', 'green time for sale', 'for emerald time', 'moment boy adjusts time again', 'A green clock'),
              'Single RNG': (False, True, None, 0x62, 'something you don\'t yet have', None, None, None, None, 'unknown boy somethings again', 'A new mystery'),
              'Multi RNG': (False, True, None, 0x63, 'something you may already have', None, None, None, None, 'unknown boy somethings again', 'A total mystery'),
              'Magic Upgrade (1/2)': (True, False, None, 0x4E, 'Half Magic!\nDouble your magic power!', 'and the spell power', 'the magic-saving kid', 'wizardry for sale', 'mekalekahi mekahiney ho', 'magic boy saves magic again', 'Half magic'),  # can be required to beat mothula in an open seed in very very rare circumstance
              'Magic Upgrade (1/4)': (True, False, None, 0x4F, 'Quarter Magic!\nMagic is basically free now!', 'and the spell power', 'the magic-saving kid', 'wizardry for sale', 'mekalekahi mekahiney ho', 'magic boy saves magic again', 'Quarter magic'),  # can be required to beat mothula in an open seed in very very rare circumstance
              'Small Key (Eastern Palace)': (False, False, 'SmallKey', 0xA2, 'A Small Key for\nDesert Palace', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Eastern Palace'),
              'Big Key (Eastern Palace)': (False, False, 'BigKey', 0x9D, 'A Big Key for\nEastern Palace', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Eastern Palace'),
              'Compass (Eastern Palace)': (False, True, 'Compass', 0x8D, 'A Compass for\nEastern Palace', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Eastern Palace'),
              'Map (Eastern Palace)': (False, True, 'Map', 0x7D, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Eastern Palace'),
              'Small Key (Desert Palace)': (False, False, 'SmallKey', 0xA3, 'A Small Key for\nDesert Palace', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Desert Palace'),
              'Big Key (Desert Palace)': (False, False, 'BigKey', 0x9C, 'A Big Key for\nDesert Palace', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Desert Palace'),
              'Compass (Desert Palace)': (False, True, 'Compass', 0x8C, 'A Compass for\nDesert Palace', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Desert Palace'),
              'Map (Desert Palace)': (False, True, 'Map', 0x7C, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Desert Palace'),
              'Small Key (Tower of Hera)': (False, False, 'SmallKey', 0xAA, 'A Small Key for\nTower of Hera', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Tower of Hera'),
              'Big Key (Tower of Hera)': (False, False, 'BigKey', 0x95, 'A Big Key for\nTower of Hera', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Tower of Hera'),
              'Compass (Tower of Hera)': (False, True, 'Compass', 0x85, 'A Compass for\nTower of Hera', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Tower of Hera'),
              'Map (Tower of Hera)': (False, True, 'Map', 0x75, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Tower of Hera'),
              'Small Key (Escape)': (False, False, 'SmallKey', 0xA0, 'A Small Key for\nEscape', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Hyrule Castle'),
              'Big Key (Escape)': (False, False, 'BigKey', 0x9F, 'A Big Key for\nEscape', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Hyrule Castle'),
              'Compass (Escape)': (False, True, 'Compass', 0x8F, 'A Compass for\nEscape', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Hyrule Castle'),
              'Map (Escape)': (False, True, 'Map', 0x7F, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Hyrule Castle'),
              'Small Key (Agahnims Tower)': (False, False, 'SmallKey', 0xA4, 'A Small Key for\nAganim\'s Tower', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Castle Tower'),
              'Small Key (Palace of Darkness)': (False, False, 'SmallKey', 0xA6, 'A Small Key for\nDark Palace', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Palace of Darkness'),
              'Big Key (Palace of Darkness)': (False, False, 'BigKey', 0x99, 'A Big Key for\nDark Palace', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Palace of Darkness'),
              'Compass (Palace of Darkness)': (False, True, 'Compass', 0x89, 'A Compass for\nDark Palace', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Palace of Darkness'),
              'Map (Palace of Darkness)': (False, True, 'Map', 0x79, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Palace of Darkness'),
              'Small Key (Thieves Town)': (False, False, 'SmallKey', 0xAB, 'A Small Key for\nThieves Town', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Thieves\' Town'),
              'Big Key (Thieves Town)': (False, False, 'BigKey', 0x94, 'A Big Key for\nThieves Town', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Thieves\' Town'),
              'Compass (Thieves Town)': (False, True, 'Compass', 0x84, 'A Compass for\nThieves Town', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Thieves\' Town'),
              'Map (Thieves Town)': (False, True, 'Map', 0x74, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Thieves\' Town'),
              'Small Key (Skull Woods)': (False, False, 'SmallKey', 0xA8, 'A Small Key for\nSkull Woods', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Skull Woods'),
              'Big Key (Skull Woods)': (False, False, 'BigKey', 0x97, 'A Big Key for\nSkull Woods', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Skull Woods'),
              'Compass (Skull Woods)': (False, True, 'Compass', 0x87, 'A Compass for\nSkull Woods', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Skull Woods'),
              'Map (Skull Woods)': (False, True, 'Map', 0x77, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Skull Woods'),
              'Small Key (Swamp Palace)': (False, False, 'SmallKey', 0xA5, 'A Small Key for\nSwamp Palace', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Swamp Palace'),
              'Big Key (Swamp Palace)': (False, False, 'BigKey', 0x9A, 'A Big Key for\nSwamp Palace', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Swamp Palace'),
              'Compass (Swamp Palace)': (False, True, 'Compass', 0x8A, 'A compass for\nSwamp Palace', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Swamp Palace'),
              'Map (Swamp Palace)': (False, True, 'Map', 0x7A, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Swamp Palace'),
              'Small Key (Ice Palace)': (False, False, 'SmallKey', 0xA9, 'A Small Key for\nIce Palace', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Ice Palace'),
              'Big Key (Ice Palace)': (False, False, 'BigKey', 0x96, 'A Big Key for\nIce Palace', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Ice Palace'),
              'Compass (Ice Palace)': (False, True, 'Compass', 0x86, 'A Compass for\nIce Palace', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Ice Palace'),
              'Map (Ice Palace)': (False, True, 'Map', 0x76, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Ice Palace'),
              'Small Key (Misery Mire)': (False, False, 'SmallKey', 0xA7, 'A Small Key for\nMisery Mire', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Misery Mire'),
              'Big Key (Misery Mire)': (False, False, 'BigKey', 0x98, 'A Big Key for\nMisery Mire', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Misery Mire'),
              'Compass (Misery Mire)': (False, True, 'Compass', 0x88, 'A Compass for\nMisery Mire', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Misery Mire'),
              'Map (Misery Mire)': (False, True, 'Map', 0x78, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Misery Mire'),
              'Small Key (Turtle Rock)': (False, False, 'SmallKey', 0xAC, 'A Small Key for\nTurtle Rock', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Turtle Rock'),
              'Big Key (Turtle Rock)': (False, False, 'BigKey', 0x93, 'A Big Key for\nTurtle Rock', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Turtle Rock'),
              'Compass (Turtle Rock)': (False, True, 'Compass', 0x83, 'A Compass for\nTurtle Rock', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'A compass to Turtle Rock'),
              'Map (Turtle Rock)': (False, True, 'Map', 0x73, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Turtle Rock'),
              'Small Key (Ganons Tower)': (False, False, 'SmallKey', 0xAD, 'A Small Key for\nGanon\'s Tower', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key to Ganon\'s Tower'),
              'Big Key (Ganons Tower)': (False, False, 'BigKey', 0x92, 'A Big Key for\nGanon\'s Tower', 'and the big key', 'the big-unlock kid', 'big key for sale', 'face key fungus', 'key boy opens chest again', 'A big key to Ganon\'s Tower'),
              'Compass (Ganons Tower)': (False, True, 'Compass', 0x82, 'A Compass for\nGanon\'s Tower', 'and the compass', 'the magnetic kid', 'compass for sale', 'magnetic fungus', 'compass boy finds boss again', 'a comapss to Ganon\'s Tower'),
              'Map (Ganons Tower)': (False, True, 'Map', 0x72, 'A tightly folded map rests here', 'and the map', 'cartography kid', 'map for sale', 'a map to shrooms', 'map boy navigates again', 'A map to Ganon\'s Tower'),
              'Small Key (Universal)': (False, True, None, 0xAF, 'A small key for any door', 'and the key', 'the unlocking kid', 'keys for sale', 'unlock the fungus', 'key boy opens door again', 'A small key'),
              'Nothing': (False, False, None, 0x5A, 'Some Hot Air', 'and the Nothing', 'the zen kid', 'outright theft', 'shroom theft', 'empty boy is bored again', 'Nothing'),
              'Red Potion': (False, False, None, 0x2E, None, None, None, None, None, None, None),
              'Green Potion': (False, False, None, 0x2F, None, None, None, None, None, None, None),
              'Blue Potion': (False, False, None, 0x30, None, None, None, None, None, None, None),
              'Bee': (False, False, None, 0x0E, None, None, None, None, None, None, None),
              'Small Heart': (False, False, None, 0x42, None, None, None, None, None, None, None),
              'Beat Agahnim 1': (True, False, 'Event', None, None, None, None, None, None, None, None),
              'Beat Agahnim 2': (True, False, 'Event', None, None, None, None, None, None, None, None),
              'Get Frog': (True, False, 'Event', None, None, None, None, None, None, None, None),
              'Return Smith': (True, False, 'Event', None, None, None, None, None, None, None, None),
              'Pick Up Purple Chest': (True, False, 'Event', None, None, None, None, None, None, None, None),
              'Open Floodgate': (True, False, 'Event', None, None, None, None, None, None, None, None),
             }
